config/routes.rb
Bookkeeper::Engine.routes.draw do
  resources :purchases
  resources :search, only: [:create]
  resources :balance, only: [:index]
  resources :incomings, except: [:index, :show]
  resources :outgoings, except: [:index, :show]
end

app/models/bookkeeper/account.rb
module Bookkeeper
  class Account < ActiveRecord::Base
    attr_accessible :title, :start_date, :initial_balance, :default

    has_many :movements, class_name: "Bookkeeper::Movement"
    has_many :incomings, class_name: "Bookkeeper::Incoming"
    has_many :outgoings, class_name: "Bookkeeper::Outgoing"

    validates :balance, numericality: { allow_nil: true }
    validates :title, presence: true, uniqueness: true
    validate :default_must_be_uniq

    before_save do
      self.update_start_date if self.start_date.blank? and !self.movements.empty?
      self.rebuild_balance
    end

    def update_balance
      self.rebuild_balance
      self.save
    end

    def rebuild_balance
      self.balance = self.initial_balance + self.incomings.sum(:amount) - self.outgoings.sum(:amount)
    end

    def update_start_date
      self.update_attribute(:start_date, self.movements.first.created_at)
    end

    def self.default
      account = Account.find_by_default(true)
      account = Account.create(title: "Default", start_date: Time.now, initial_balance: 0.0, default: true) if account.nil?

      account
    end

    protected

    def default_must_be_uniq
      errors.add(:base, I18n.t(".default_must_be_uniq")) if Account.find_by_default(true)
    end
  end
end

app/models/bookkeeper/categories.rb
module Bookkeeper
  class Categories < ActiveRecord::Base
    attr_accessible :name

    belongs_to :categorizable, polymorphic: true

    validates :name, presence: true, uniqueness: true
  end
end

app/models/bookkeeper/incoming.rb
module Bookkeeper
  class Incoming < Movement
  end
end

app/models/bookkeeper/movement.rb
module Bookkeeper
  class Movement < ActiveRecord::Base
    attr_accessible :amount, :description, :date

    belongs_to :account, class_name: "Bookkeeper::Account"
    has_many :categories, as: :categorizable

    validates :amount, presence: true, numericality: true
    validates :description, presence: true
    validate :amount_cannot_be_zero
    validates :account, presence: true
    validates :date, presence: true

    scope :ordered, order('date ASC, created_at ASC')
    scope :reverse_ordered, order('date DESC, created_at DESC')

    before_validation do
      self.account = Account.default unless self.account
    end

    after_save do
      self.account.update_balance
    end

    after_destroy do
      self.account.update_balance
    end

    def incoming?
      self.class == Bookkeeper::Incoming
    end

    protected

    def amount_cannot_be_zero
      if !amount.blank? && amount == 0
        errors.add(:amount, I18n.t(".cannot_be_zero"))
      end
    end
  end
end

app/models/bookkeeper/outgoing.rb
module Bookkeeper
  class Outgoing < Movement
  end
end

app/models/bookkeeper/purchase.rb
module Bookkeeper
  class Purchase < ActiveRecord::Base
    mount_uploader :receipt, ReceiptUploader

    attr_accessible :description, :purchase_date, :title, :warranty_duration, :receipt, :invoice, :amount

    has_many :categories, as: :categorizable

    validates_presence_of :title
    validates_numericality_of :warranty_duration, allow_nil: true
    validates_numericality_of :amount, allow_nil: true
    validates_date :purchase_date, allow_nil: true, allow_blank: true

    default_scope order('created_at DESC')
  end
end

app/controllers/bookkeeper/application_controller.rb
module Bookkeeper
  class ApplicationController < ActionController::Base
    layout 'application'
  end
end

app/controllers/bookkeeper/balance_controller.rb
require_dependency "bookkeeper/application_controller"

module Bookkeeper
  class BalanceController < ApplicationController
    def index
      @account = Account.default
      @movements = @account.movements
    end
  end
end

app/controllers/bookkeeper/incomings_controller.rb
require_dependency "bookkeeper/application_controller"

module Bookkeeper
  class IncomingsController < ApplicationController
    def new
      @incoming = Incoming.new
    end

    def edit
      @incoming = Incoming.find(params[:id])
    end

    def create
      @incoming = Incoming.new(params[:incoming])

      if @incoming.save
        redirect_to balance_index_path, notice: I18n.t('.bookkeeper.controllers.incomings.created')
      else
        render action: "new"
      end
    end

    def update
      @incoming = Incoming.find(params[:id])

      if @incoming.update_attributes(params[:incoming])
        redirect_to balance_index_path, notice: I18n.t('.bookkeeper.controllers.incomings.updated')
      else
        render action: "edit"
      end
    end

    def destroy
      @incoming = Incoming.find(params[:id])
      @incoming.destroy
      flash[:notice] = I18n.t('.bookkeeper.controllers.incomings.destroyed')

      redirect_to balance_index_path
    end
  end
end

app/controllers/bookkeeper/outgoings_controller.rb
require_dependency "bookkeeper/application_controller"

module Bookkeeper
  class OutgoingsController < ApplicationController
    def new
      @outgoing = Outgoing.new
    end

    def edit
      @outgoing = Outgoing.find(params[:id])
    end

    def create
      @outgoing = Outgoing.new(params[:outgoing])

      if @outgoing.save
        redirect_to balance_index_path, notice: I18n.t('.bookkeeper.controllers.outgoings.created')
      else
        render action: "new"
      end
    end

    def update
      @outgoing = Outgoing.find(params[:id])

      if @outgoing.update_attributes(params[:outgoing])
        redirect_to balance_index_path, notice: I18n.t('.bookkeeper.controllers.outgoings.updated')
      else
        render action: "edit"
      end
    end

    def destroy
      @outgoing = Outgoing.find(params[:id])
      @outgoing.destroy
      flash[:notice] = I18n.t('.bookkeeper.controllers.outgoings.destroyed')

      redirect_to balance_index_path
    end
  end
end

app/controllers/bookkeeper/purchases_controller.rb
require_dependency "bookkeeper/application_controller"

module Bookkeeper
  class PurchasesController < ApplicationController
    def index
      @purchases = Purchase.all

      respond_to do |format|
        format.html
        format.json { render json: @purchases }
      end
    end

    def show
      @purchase = Purchase.find(params[:id])

      respond_to do |format|
        format.html
        format.json { render json: @purchase }
      end
    end

    def new
      @purchase = Purchase.new

      respond_to do |format|
        format.html
        format.json { render json: @purchase }
      end
    end

    def edit
      @purchase = Purchase.find(params[:id])
    end

    def create
      @purchase = Purchase.new(params[:purchase])

      respond_to do |format|
        if @purchase.save
          format.html { redirect_to purchases_path, notice: I18n.t('.bookkeeper.controllers.purchases.created') }
          format.json { render json: @purchase, status: :created, location: @purchase }
        else
          format.html { render action: "new" }
          format.json { render json: @purchase.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      @purchase = Purchase.find(params[:id])

      respond_to do |format|
        if @purchase.update_attributes(params[:purchase])
          format.html { redirect_to purchases_path, notice: I18n.t('.bookkeeper.controllers.purchases.updated') }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @purchase.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @purchase = Purchase.find(params[:id])
      @purchase.destroy
      flash[:notice] = I18n.t('.bookkeeper.controllers.purchases.destroyed')

      respond_to do |format|
        format.html { redirect_to purchases_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/bookkeeper/search_controller.rb
require_dependency "bookkeeper/application_controller"

module Bookkeeper
  class SearchController < ApplicationController
    def create
      @q = params[:search][:q]
      query = "%#{@q}%"
      @results = Purchase.where("title LIKE ? OR description LIKE ?", query, query)
    end
  end
end

app/helpers/bookkeeper/application_helper.rb
module Bookkeeper
  module ApplicationHelper
  end
end

app/views/bookkeeper/balance/_balance_chart.html.erb
<% content_for :javascripts do %>
  <script type="text/javascript">
    google.setOnLoadCallback(drawBalanceChart);
    function drawBalanceChart() {
        var data = google.visualization.arrayToDataTable([
          ['<%=t ".date" %>', null],
          <% balance = @account.initial_balance %>
          ['<%= @account.start_date.strftime("%d/%m/%Y") %>', <%= balance %> ],
          <% @movements.ordered.each do |movement| %>
            <% movement.incoming? ? (balance += movement.amount) : (balance -= movement.amount) %>
            ['<%= movement.date.strftime("%d/%m/%Y") %>', <%= balance %> ],
          <% end %>
        ]);

        var options = {
          title: '<%=t ".title" %>',
          colors: ['#F89406']
        };

        var chart = new google.visualization.LineChart(document.getElementById('balance_chart'));
        chart.draw(data, options);
      }

  </script>
<% end %>

app/views/bookkeeper/balance/_movements_chart.html.erb
<% content_for :javascripts do %>
  <script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
    google.setOnLoadCallback(drawMovementsChart);
    function drawMovementsChart() {
      var data = new google.visualization.DataTable();
      data.addColumn('string', '<%= t ".date" %>');
      data.addColumn('number', '<%= t ".movement" %>');
      data.addRows([
        <% @movements.ordered.each do |movement| %>
          <% if movement.incoming? %>
            ['<%= movement.date.strftime("%d/%m/%Y") %>', <%= movement.amount %> ],
          <% else %>
            ['<%= movement.date.strftime("%d/%m/%Y") %>', <%= -movement.amount %> ],
          <% end %>
        <% end %>
      ]);

      var options = {
        isStacked: true,
        title: '<%=t ".title" %>',
        colors: ['#468847', '#F89406'],
        chartArea: { top: 30 },
        hAxis: { format:'#.##€' },
      };

      var view = new google.visualization.DataView(data);
      view.setColumns([0, {
          type: 'number',
          label: null,
          calc: function (dt, row) {
              return (dt.getValue(row, 1) > 0) ? dt.getValue(row, 1) : null;
          }
        }, {
          type: 'number',
          label: null,
          calc: function (dt, row) {
              return (dt.getValue(row, 1) <  0) ? dt.getValue(row, 1) : null;
          }
      }]);
      var chart = new google.visualization.BarChart(document.getElementById('movements_chart'));
      chart.draw(view, options);
    }
  </script>
<% end %>

app/views/bookkeeper/balance/index.html.erb
<h1><%= t '.title' %></h1>

<div class="row">
  <div class="span3">
    <h3><%=t '.account_balance' %></h3>
    <p><%= number_to_currency @account.balance %></p>
  </div>
  <div id="balance_chart" class="span9" style="height: 300px;"></div>
</div>

<div class="row">
  <div class="span6">
    <table class='table table-striped table-condensed table-bordered'>
      <thead>
        <tr>
          <th><%=t 'bookkeeper.models.movement.attributes.amount' %></th>
          <th><%=t 'bookkeeper.models.movement.attributes.description' %></th>
          <th><%=t 'bookkeeper.models.movement.attributes.date' %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @movements.reverse_ordered.each do |movement| %>
          <tr>
            <td>
              <span class="label label-<%= movement.incoming? ? "success" : "warning" %>"><%= (movement.incoming? ? '<i class="icon-circle-arrow-down"></i>' : '<i class="icon-circle-arrow-up"></i>').html_safe %></span>
              <%= number_to_currency movement.amount %></td>
            <td><%= movement.description %></td>
            <td><%=l movement.date, format: :short rescue '' %></td>
            <td>
              <% if movement.incoming? %>
                <%= link_to ('<i class="icon-pencil"></i> ' + t('bookkeeper.actions.edit')).html_safe, edit_incoming_path(movement), class: 'btn btn-mini' %>
              <% else %>
                <%= link_to ('<i class="icon-pencil"></i> ' + t('bookkeeper.actions.edit')).html_safe, edit_outgoing_path(movement), class: 'btn btn-mini' %>
              <% end %>
              <%= link_to ('<i class="icon-remove"></i> ' + t('bookkeeper.actions.destroy')).html_safe, movement, method: :delete, data: { confirm: t('bookkeeper.actions.destroy_confirm', default: 'Are you sure?') }, class: 'btn btn-mini btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br />

    <%= link_to ('<i class="icon-circle-arrow-down"></i> ' + t('.new_incoming')).html_safe, new_incoming_path, class: 'btn btn-success' %>
    <%= link_to ('<i class="icon-circle-arrow-up"></i> ' + t('.new_outgoing')).html_safe, new_outgoing_path, class: 'btn btn-warning' %>
  </div>
  <div id="movements_chart" class="span6" style="height: 500px;"></div>
</div>


<% content_for :javascripts do %>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
<% end %>
<%= render partial: "movements_chart" %>
<%= render partial: "balance_chart" %>

app/views/bookkeeper/incomings/_form.html.erb
<%= simple_form_for @incoming, html: { class: 'form-horizontal' } do |f| %>
  <%= render partial: 'bookkeeper/shared/movement_form', locals: { f: f } %>
<% end %>

app/views/bookkeeper/incomings/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to ('<i class="icon-arrow-left"></i> ' + t('bookkeeper.actions.back')).html_safe, balance_index_path, class: 'btn' %>

app/views/bookkeeper/incomings/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to ('<i class="icon-arrow-left"></i> ' + t('bookkeeper.actions.back')).html_safe, balance_index_path, class: 'btn' %>

app/views/bookkeeper/movements/_search.html.erb
<div class="pull-right">
  <%= form_tag search_index_path, class: "navbar-search pull-left" do %>
    <%= text_field_tag 'search[q]', '', class: 'search-query', placeholder: t('.search') %>
  <% end %>
</div>

app/views/bookkeeper/movements/index.html.erb
<%= render partial: 'search' %>
<h1><%= t '.title' %></h1>

<table class='table table-striped table-condensed table-bordered'>
  <thead>
    <tr>
      <th><%=t 'bookkeeper.models.purchase.attributes.title' %></th>
      <th><%=t 'bookkeeper.models.purchase.attributes.description' %></th>
      <th><%=t 'bookkeeper.models.purchase.attributes.purchase_date' %></th>
      <th><%=t 'bookkeeper.models.purchase.attributes.warranty_duration' %></th>
      <th><%=t 'bookkeeper.models.purchase.attributes.receipt' %></th>
      <th><%=t 'bookkeeper.models.purchase.attributes.updated_at' %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.title %></td>
        <td><%= purchase.description %></td>
        <td><%=l purchase.purchase_date rescue '' %></td>
        <td><%= purchase.warranty_duration %> <%=t '.months' %></td>
        <td><%= link_to "<i class='icon-download-alt'></i> #{purchase.receipt.file.filename}".html_safe, purchase.receipt.url, class: 'btn btn-mini' if purchase.receipt.file %></td>
        <td><%=l purchase.updated_at, format: :short rescue '' %></td>
        <td>
          <%= link_to ('<i class="icon-pencil"></i> ' + t('bookkeeper.actions.edit')).html_safe, edit_purchase_path(purchase), class: 'btn btn-mini' %>
          <%= link_to ('<i class="icon-remove"></i> ' + t('bookkeeper.actions.destroy')).html_safe, purchase, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to ('<i class="icon-plus"></i> ' + t('bookkeeper.actions.new')).html_safe, new_purchase_path, class: 'btn' %>

app/views/bookkeeper/outgoings/_form.html.erb
<%= simple_form_for @outgoing,  html: { class: 'form-horizontal' } do |f| %>
  <%= render partial: 'bookkeeper/shared/movement_form', locals: { f: f } %>
<% end %>

app/views/bookkeeper/outgoings/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to ('<i class="icon-arrow-left"></i> ' + t('bookkeeper.actions.back')).html_safe, balance_index_path, class: 'btn' %>

app/views/bookkeeper/outgoings/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to ('<i class="icon-arrow-left"></i> ' + t('bookkeeper.actions.back')).html_safe, balance_index_path, class: 'btn' %>

app/views/bookkeeper/purchases/_form.html.erb
<%= simple_form_for @purchase, html: { class: 'form-horizontal' } do |f| %>

  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description, input_html: { class: 'input-xxlarge', rows: 4 } %>
    <%= f.input :purchase_date, :wrapper => :prepend do %>
      <%= content_tag :span, '<i class="icon-calendar"></i>'.html_safe, class: "add-on calendar" %>
      <%= f.input_field :purchase_date, as: :datepicker, data: { 'date-format' => 'dd/mm/yyyy' } %>
    <% end %>
    <%= f.input :invoice %>
    <%= f.input :amount, :wrapper => :prepend do %>
      <%= content_tag :span, '<i class="icon-money"></i>'.html_safe, class: "add-on calendar" %>
      <%= f.input_field :amount, class: "input-mini" %>
    <% end %>
    <%= f.input :warranty_duration, collection: [["6 #{t('simple_form.labels.purchase.months')}", 6], ["1 #{t('simple_form.labels.purchase.year')}", 12], ["2 #{t('simple_form.labels.purchase.years')}", 24], ["3 #{t('simple_form.labels.purchase.years')}", 36]], input_html: { class: 'input-small' } %>
    <%= f.input :receipt %>
  </div>
  <div class="form-actions">
    <%= button_tag ('<i class="icon-ok"></i> ' + t('bookkeeper.actions.save')).html_safe, class: 'btn' %>
  </div>
<% end %>

app/views/bookkeeper/purchases/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to ('<i class="icon-search"></i> ' + t('bookkeeper.actions.show')).html_safe, @purchase, class: 'btn' %>
<%= link_to ('<i class="icon-arrow-left"></i> ' + t('bookkeeper.actions.back')).html_safe, purchases_path, class: 'btn' %>

app/views/bookkeeper/purchases/index.html.erb
<%= render partial: 'search' %>
<h1><%= t '.title' %></h1>

<table class='table table-striped table-condensed table-bordered'>
  <thead>
    <tr>
      <th><%=t 'bookkeeper.models.purchase.attributes.title' %></th>
      <th><%=t 'bookkeeper.models.purchase.attributes.description' %></th>
      <th><%=t 'bookkeeper.models.purchase.attributes.purchase_date' %></th>
      <th><%=t 'bookkeeper.models.purchase.attributes.warranty_duration' %></th>
      <th><%=t 'bookkeeper.models.purchase.attributes.receipt' %></th>
      <th><%=t 'bookkeeper.models.purchase.attributes.updated_at' %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.title %></td>
        <td><%= purchase.description %></td>
        <td><%=l purchase.purchase_date rescue '' %></td>
        <td><%= purchase.warranty_duration %> <%=t '.months' %></td>
        <td><%= link_to "<i class='icon-download-alt'></i> #{purchase.receipt.file.filename}".html_safe, purchase.receipt.url, class: 'btn btn-mini' if purchase.receipt.file %></td>
        <td><%=l purchase.updated_at, format: :short rescue '' %></td>
        <td>
          <%= link_to ('<i class="icon-pencil"></i> ' + t('bookkeeper.actions.edit')).html_safe, edit_purchase_path(purchase), class: 'btn btn-mini' %>
          <%= link_to ('<i class="icon-remove"></i> ' + t('bookkeeper.actions.destroy')).html_safe, purchase, method: :delete, data: { confirm: t('bookkeeper.actions.destroy_confirm', default: 'Are you sure?') }, class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to ('<i class="icon-plus"></i> ' + t('bookkeeper.actions.new')).html_safe, new_purchase_path, class: 'btn' %>

app/views/bookkeeper/purchases/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to ('<i class="icon-arrow-left"></i> ' + t('bookkeeper.actions.back')).html_safe, purchases_path, class: 'btn' %>

app/views/bookkeeper/search/create.html.erb
<h1><%= t '.title', q: @q %></h1>

<table class='table table-striped table-condensed table-bordered'>
  <thead>
    <tr>
      <th><%=t 'bookkeeper.models.purchase.attributes.title' %></th>
      <th><%=t 'bookkeeper.models.purchase.attributes.description' %></th>
      <th><%=t 'bookkeeper.models.purchase.attributes.purchase_date' %></th>
      <th><%=t 'bookkeeper.models.purchase.attributes.warranty_duration' %></th>
      <th><%=t 'bookkeeper.models.purchase.attributes.receipt' %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @results.each do |purchase| %>
      <tr>
        <td><%= purchase.title %></td>
        <td><%= purchase.description %></td>
        <td><%=l purchase.purchase_date rescue '' %></td>
        <td><%= purchase.warranty_duration %> <%=t '.months' %></td>
        <td><%= link_to "<i class='icon-download-alt'></i> #{purchase.receipt.file.filename}".html_safe, purchase.receipt.url, class: 'btn btn-mini' if purchase.receipt.file %></td>
        <td>
          <%= link_to ('<i class="icon-pencil"></i> ' + t('bookkeeper.actions.edit')).html_safe, edit_purchase_path(purchase), class: 'btn btn-mini' %>
          <%= link_to ('<i class="icon-remove"></i> ' + t('bookkeeper.actions.destroy')).html_safe, purchase, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<%= link_to ('<i class="icon-arrow-left"></i> ' + t('bookkeeper.actions.back')).html_safe, purchases_path, class: 'btn' %>

app/views/bookkeeper/shared/_movement_form.html.erb
<%= f.error_notification %>

<div class="form-inputs">
  <%= f.input :amount, :wrapper => :append do %>
    <%= f.input_field :amount, class: "input-mini" %>
    <%= content_tag :span, '&euro;'.html_safe, class: "add-on" %>
  <% end %>
  <%= f.input :description, input_html: { class: 'input-xxlarge' } %>
  <%= f.input :date, :wrapper => :prepend do %>
    <%= content_tag :span, '<i class="icon-calendar"></i>'.html_safe, class: "add-on calendar" %>
    <%= f.input_field :date, as: :datepicker, data: { 'date-format' => 'dd/mm/yyyy' } %>
  <% end %>
</div>
<div class="form-actions">
  <%= button_tag ('<i class="icon-ok"></i> ' + t('bookkeeper.actions.save')).html_safe, class: 'btn' %>
</div>

app/views/layouts/bookkeeper/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookkeeper</title>
  <%= stylesheet_link_tag    "bookkeeper/application", :media => "all" %>
  <%= javascript_include_tag "bookkeeper/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>